# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Vavidoprj/chuot/chuot.cache/wt [current_project]
set_property parent.project_path E:/Vavidoprj/chuot/chuot.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
read_vhdl -library xil_defaultlib {
  E:/Vavidoprj/chuot/chuot.srcs/sources_1/imports/chuot/Ps2Interface.vhd
  E:/Vavidoprj/chuot/x47segdriver.vhd
  E:/Vavidoprj/chuot/chuot.srcs/sources_1/imports/chuot/MouseCtl.vhd
  E:/Vavidoprj/chuot/chuot.srcs/sources_1/new/top.vhd
}
read_xdc E:/Vavidoprj/chuot/chuot.srcs/constrs_1/new/chuot.xdc
set_property used_in_implementation false [get_files E:/Vavidoprj/chuot/chuot.srcs/constrs_1/new/chuot.xdc]

catch { write_hwdef -file top.hwdef }
synth_design -top top -part xc7a35tcpg236-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
